import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Guia Livreiro</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Arvo:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="flex h-[100vh] w-[100vw] items-center justify-center gap-5 bg-[#272727] p-5">
        <div className="h-[30rem] w-[9rem] bg-slate-500"></div>
        <div className="flex h-[78.125%] w-[78.125%] flex-col items-center  justify-evenly bg-[#C4C4C4] bg-[url('../../public/papertexture.png')] bg-cover">
          <h1
            style={{ fontFamily: "Arvo" }}
            className="text-center text-5xl text-[#272727]"
          >
            Guia<strong>Livreiro</strong>
          </h1>
          <div className="flex w-1/4 items-center">
            <Image
              alt=""
              src="/search.svg"
              width={15}
              height={15}
              className="absolute ml-3"
            />
            <input
              type="text"
              className="rounded-2xl border-2 border-[#272727] bg-transparent px-2 py-1 pl-8 outline-none placeholder:text-[#666]"
              placeholder="Procure o nome do livro"
            />
          </div>
          <p className="w-2/3 text-center text-[#272727]">
            Bem-vindo ao nosso site de informações sobre livros! Aqui,
            oferecemos informações precisas e atualizadas sobre títulos, autores
            e sinopses para ajudar na escolha de livros para venda. Realize suas
            pesquisas de forma simples e eficiente, sem precisar se cadastrar.
            Encontre as informações que você precisa para ajudar em suas vendas
            de livros agora mesmo.
          </p>
        </div>
        <div className="h-[30rem] w-[9rem] bg-slate-500"></div>
      </main>
    </>
  );
};

export default Home;
