import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Adsense from "../components/ad";

const Home: NextPage = () => {
  const [search, setSearch] = useState("");
  const [mobile, setMobile] = useState(false);

  useEffect(() => {
    function isMobile() {
      return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
        navigator.userAgent
      );
    }
    setMobile(isMobile());
  }, [mobile]);

  const router = useRouter();
  const handleSearch = (key: string) => {
    if (key === "Enter") {
      void router.push(`/search/${search}`);
    }
  };

  return (
    <>
      <Head>
        <title>Guia Livreiro</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Arvo:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="my-auto flex items-center justify-between px-1 max-sm:flex-col max-sm:gap-4">
        <Adsense />
        <div className="flex h-[70vh] w-[78.125vw] flex-col items-center justify-between max-sm:w-[90vw]">
          <div className="flex flex-col items-center">
            <div className="relative h-[6rem] w-[6rem] max-md:h-[4rem] max-md:w-[4rem]">
              <Image
                src="/logo.svg"
                alt="logo"
                fill
                className="object-cover drop-shadow-custom"
              />
            </div>
            <h1
              style={{ fontFamily: "Arvo" }}
              className="text-center text-7xl text-[#272727] drop-shadow-custom max-md:text-5xl"
            >
              Guia<strong>Livreiro</strong>
            </h1>
          </div>

          <div className="flex w-[20rem] flex-col items-center justify-center">
            <Image
              alt=""
              src="/search.svg"
              width={16}
              height={16}
              className="absolute mr-[285px] max-sm:mb-[50px]"
            />
            <input
              type="text"
              className="w-full rounded-2xl border-2 border-[#272727] bg-transparent py-1 px-8 outline-none placeholder:text-center placeholder:text-[#666]"
              placeholder="Procure o nome do livro"
              value={search}
              onChange={({ target }) => setSearch(target.value)}
              onKeyDown={({ key }) => handleSearch(key)}
            />
            {mobile && (
              <button
                className="mt-2 rounded-full border-2 border-[#272727] p-2"
                onClick={() => handleSearch("Enter")}
              >
                Procurar
              </button>
            )}
          </div>
          <p className="w-2/3 text-center italic text-[#272727] drop-shadow-custom max-sm:w-full">
            Bem-vindo ao nosso site de informações sobre livros! Aqui,
            oferecemos informações precisas e atualizadas sobre títulos, autores
            e sinopses para ajudar na escolha de livros para venda. Realize suas
            pesquisas de forma simples e eficiente, sem precisar se cadastrar.
            Encontre as informações que você precisa para ajudar em suas vendas
            de livros agora mesmo.
          </p>
        </div>
        <Adsense />
      </main>
    </>
  );
};

export default Home;
