import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

const Header: NextPage<{ search: string; onSearch: (key: string) => void }> = ({
  search,
  onSearch,
}) => {
  const [input, setInput] = useState("");
  const [mobile, setMobile] = useState(false);

  useEffect(() => {
    function isMobile() {
      return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
        navigator.userAgent
      );
    }
    setMobile(isMobile());
  }, [mobile]);

  const handleSearch = (key: string) => {
    if (key === "Enter") {
      onSearch(input);
    }
  };

  return (
    <>
      <Head>
        <title>Guia Livreiro</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Arvo:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="flex h-28 items-center justify-between">
        <Link
          href="/"
          className="relative h-[5rem] w-[5rem] max-sm:h-[4rem] max-sm:w-[4rem]"
        >
          <Image
            src="/logo.svg"
            alt="logo"
            fill
            className="object-cover drop-shadow-custom"
          />
        </Link>
        <div className="flex w-[20rem] items-center justify-center max-sm:w-[12.5rem] max-sm:flex-col">
          <Image
            alt=""
            src="/search.svg"
            width={16}
            height={16}
            className="absolute mr-[285px] h-auto w-auto max-sm:mr-[160px] max-sm:mb-[40px]"
            sizes=""
          />
          <input
            type="text"
            className="w-full rounded-2xl border-2 border-[#272727] bg-transparent px-2 py-1 pl-8 outline-none placeholder:text-[#666]"
            placeholder={search}
            value={input}
            onChange={({ target }) => setInput(target.value)}
            onKeyDown={({ key }) => handleSearch(key)}
          />
          {mobile && (
            <button
              onClick={() => handleSearch("Enter")}
              className="mt-1 self-end rounded-full border-2 border-[#272727] p-1"
            >
              Pesquisar
            </button>
          )}
        </div>
      </div>
    </>
  );
};

export default Header;
